[versions]
asm = "9.2"
javaparser = "3.24.2"


[libraries]
# com.github.javaparser:javaparser-core - JavaParser
javaparser-core = { module = "com.github.javaparser:javaparser-core", version.ref = "javaparser" }

# org.ow2.asm - ASM
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }