name: CI
on:
  - pull_request
  - push
  - workflow_dispatch


env:
  JDK_VERSION: "19"


jobs:
  validate-gradle:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1


  build:
    name: Build
    needs: [validate-gradle]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ env.JDK_VERSION }}

      - name: Gradle Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -Psnapshot --info -S --show-version
          gradle-home-cache-cleanup: true